import typeChart from '@/data/typeChart.json';
import defensiveTypeChart from '@/data/defensiveTypeChart.json';
import typesData from '@/data/types.json';

export const dynamic = 'force-static';

export function GET() {
  const data = JSON.stringify({ types: typesData.types, defensive: defensiveTypeChart, offensive: typeChart }).replace(/</g, '\\u003c');
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Pokemon Type Matchup Calculator</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f8fafc;color:#172033;font:15px/1.45 system-ui,-apple-system,sans-serif}.w{max-width:760px;margin:auto;padding:16px}.card{background:white;border:1px solid #cbd5e1;border-radius:14px;padding:20px;box-shadow:0 4px 18px #0f172a12}h1{font-size:24px;margin:0 0 6px}p{margin:0 0 16px;color:#475569}.selects{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{font-weight:650}select{display:block;width:100%;min-height:44px;margin-top:6px;padding:8px;border:1px solid #94a3b8;border-radius:8px;background:white}.result{margin-top:18px;display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.group{border-radius:10px;padding:12px}.group h2{font-size:15px;margin:0 0 8px}.bad{background:#fef2f2}.good{background:#f0fdf4}.immune{background:#f1f5f9}.tags{display:flex;flex-wrap:wrap;gap:6px}.tag{color:white;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:700}.foot{margin-top:16px;font-size:13px;color:#64748b}.foot a{color:#1d4ed8;font-weight:700}@media(max-width:560px){.selects,.result{grid-template-columns:1fr}.w{padding:8px}.card{padding:15px}}</style></head>
<body><main class="w"><section class="card"><h1>Pokemon Type Matchup Calculator</h1><p>Select one or two defending types to see weaknesses, resistances, and immunities.</p><div class="selects"><label>Primary type<select id="a"></select></label><label>Secondary type<select id="b"><option value="">None</option></select></label></div><div id="result" class="result" aria-live="polite"></div><div class="foot">Standard modern type chart. Abilities, items, Tera types, and game-specific rules may change a matchup. <a href="https://www.typematchup.org/" target="_blank" rel="noopener">Open full TypeMatchup tools →</a></div></section></main>
<script>const D=${data};const a=document.querySelector('#a'),b=document.querySelector('#b'),out=document.querySelector('#result');for(const t of D.types){a.add(new Option(t.name,t.id));b.add(new Option(t.name,t.id))}a.value='fire';b.value='flying';function mult(atk,defs){let m=1;for(const d of defs){const x=D.defensive[d];if(x.immuneTo.includes(atk))m*=0;else if(x.weakTo.includes(atk))m*=2;else if(x.resistsTo.includes(atk))m*=.5}return m}function render(){if(a.value===b.value)b.value='';const groups={four:[],two:[],half:[],quarter:[],zero:[]};for(const t of D.types){const m=mult(t.id,[a.value,b.value].filter(Boolean));if(m===4)groups.four.push(t);else if(m===2)groups.two.push(t);else if(m===.5)groups.half.push(t);else if(m===.25)groups.quarter.push(t);else if(m===0)groups.zero.push(t)}const rows=[['four','4× weak','bad'],['two','2× weak','bad'],['half','½× resistant','good'],['quarter','¼× resistant','good'],['zero','Immune','immune']];out.innerHTML=rows.filter(([k])=>groups[k].length).map(([k,label,cls])=>'<section class="group '+cls+'"><h2>'+label+'</h2><div class="tags">'+groups[k].map(t=>'<span class="tag" style="background:'+t.color+'">'+t.name+'</span>').join('')+'</div></section>').join('')}a.onchange=render;b.onchange=render;render();</script></body></html>`;
  return new Response(html, { headers: { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'public, max-age=3600, s-maxage=86400', 'content-security-policy': "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; frame-ancestors *; base-uri 'none'; form-action 'none'", 'x-robots-tag': 'noindex, nofollow' } });
}
