import type { Metadata } from 'next';
import Link from 'next/link';
import TeamTypeCalculator from '@/components/TeamTypeCalculator';
import ToolNetwork from '@/components/ToolNetwork';
import JsonLd from '@/components/SEO/JsonLd';

const faqs = [
  ['What does this Pokémon type coverage calculator check?', 'It counts how many team members are weak, resistant, or immune to each attacking type and highlights weaknesses without a defensive answer.'],
  ['Can I enter six Pokémon?', 'Yes. Enter the current defensive typing for up to six team members. Use the exact regional or alternate form that will enter battle.'],
  ['Does this calculate offensive move coverage?', 'This version focuses on defensive team coverage: safe switches, shared weaknesses, resistances, and immunities. Move coverage, stats, abilities, and format legality require separate checks.'],
  ['Do abilities and Tera types change the result?', 'Yes. Enter a transformed defensive type when planning a Tera state, and review ability-specific immunities separately because this chart uses standard type relationships.'],
];
export const metadata: Metadata = { title:'Pokemon Type Coverage Calculator — Team Weakness Checker', description:'Free Pokemon type coverage calculator for up to six team members. Find shared weaknesses, resistances, immunities, and defensive coverage gaps.', alternates:{canonical:'/type-coverage-calculator'} };
export default function Page(){return <main className="container mx-auto px-4 py-8"><JsonLd data={{'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Pokemon Type Coverage Calculator',url:'https://www.typematchup.org/type-coverage-calculator',applicationCategory:'GameApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{'@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]}}/><header className="mx-auto mb-8 max-w-4xl text-center"><h1 className="text-3xl sm:text-5xl font-bold">Pokemon Type Coverage Calculator</h1><p className="mt-4 text-lg text-gray-700">Build a six-member defensive type profile and find repeated weaknesses, safe switches, and uncovered threats.</p></header><div className="mx-auto max-w-5xl"><TeamTypeCalculator/></div><article className="prose max-w-4xl mx-auto mt-12"><h2>How to Analyze Team Type Coverage</h2><p>Enter each member&apos;s actual defensive type or types. Start with attacks that threaten several members, then check whether anyone resists or ignores that attack. A resistance count is useful only when that teammate can realistically switch in.</p><h2>Shared Weaknesses and Coverage Gaps</h2><p>A shared weakness is not automatically fatal, but a repeated weakness with no resistance or immunity creates a clear pressure point. Replace a member, adjust a form, or add a partner that can absorb the attack and still perform the roles your format requires.</p><h2>Defensive Coverage Versus Offensive Coverage</h2><p>This tool evaluates incoming attacks. Offensive coverage asks which targets your selected moves can hit. After correcting defensive gaps, use the <Link href="/type-effectiveness-calculator">effectiveness calculator</Link> and full matrix to inspect important attacking interactions.</p><h2>Abilities, Items, and Terastallization</h2><p>Levitate, absorption abilities, resistance berries, Air Balloon, weather, and Tera types can change practical matchups. The report deliberately begins with the standard chart so its calculation remains transparent; apply battle-specific mechanics afterward.</p><h2>Coverage Calculator FAQ</h2>{faqs.map(([q,a])=><section key={q}><h3>{q}</h3><p>{a}</p></section>)}</article><ToolNetwork current="/type-coverage-calculator"/></main>}
