import { A2A_ENDPOINT, AUTH_MD_URL, AS_URL, MCP_ENDPOINT, PRM_URL, REPO_URL, SITE } from './agentReady';

/**
 * auth.md — the WorkOS "auth.md" agent-registration convention.
 *
 * TypeMatchup is public and read-only: no credentials exist today. This file is
 * published as a DISCLOSED placeholder so agents and discovery tooling can find a
 * stable reserved contract. Every endpoint named below returns HTTP 503 until the
 * authorization server is deployed, and the file says so prominently at the top.
 */

export const AUTH_MD = [
  '# auth.md',
  '',
  '> **Status: under construction. Nothing in this file is live.**',
  '>',
  '> TypeMatchup is a public, read-only API. Every capability on ' + SITE + ' works anonymously',
  '> today: ' + MCP_ENDPOINT + ', ' + A2A_ENDPOINT + ' and the HTTP API need no registration and no',
  '> credentials. This file is published as a declared, reserved placeholder so that agents and',
  '> discovery tooling can find a stable contract while the authorization server is built.',
  '>',
  '> **Every endpoint named below currently returns HTTP 503.** Do not send credentials, identity',
  '> assertions or personal data to them. They are reserved identifiers, not running services.',
  '',
  'Live, unauthenticated capabilities are listed in section 0. The rest of the file is planned.',
  '',
  '## 0. What works right now (no auth)',
  '',
  '| Capability | Endpoint | Auth |',
  '| --- | --- | --- |',
  '| MCP server (Streamable HTTP) | `' + MCP_ENDPOINT + '` | none |',
  '| A2A endpoint (JSON-RPC) | `' + A2A_ENDPOINT + '` | none |',
  '| Pokemon / type search | `GET ' + SITE + '/api/agent/search?q=` | none |',
  '| OpenAPI 3.1 description | `' + SITE + '/openapi.json` | none |',
  '',
  'Anonymous access is rate-limited at the edge. On HTTP 429, back off exponentially.',
  '',
  '## 1. Discover',
  '',
  'Two hops, once the authorization server is live:',
  '',
  '1. Read the Protected Resource Metadata (PRM):',
  '',
  '```http',
  'GET ' + PRM_URL + ' HTTP/1.1',
  'Host: www.typematchup.org',
  '```',
  '',
  '   Use `resource`, `resource_name`, `authorization_servers`, `scopes_supported` and',
  '   `bearer_methods_supported`. (A `WWW-Authenticate: Bearer resource_metadata="..." header on a',
  '   401 response is the preferred entry point once auth is enforced.)',
  '',
  '2. Read the Authorization Server metadata and its `agent_auth` block:',
  '',
  '```http',
  'GET ' + AS_URL + ' HTTP/1.1',
  'Host: www.typematchup.org',
  '```',
  '',
  '   Fields an agent must read: `issuer`, `token_endpoint`, `revocation_endpoint`,',
  '   `grant_types_supported`, and the full `agent_auth` block — `skill`, `identity_endpoint`,',
  '   `claim_endpoint`, `events_endpoint`, `identity_types_supported`,',
  '   `identity_assertion.assertion_types_supported` and `events_supported`.',
  '',
  '   All of them are present today and every one is flagged `under_construction`.',
  '',
  '## 2. Pick a method',
  '',
  '| The agent has | Use | Ceremony |',
  '| --- | --- | --- |',
  '| A session exchangeable for an ID-JAG bound to this audience | `identity_assertion` | none |',
  '| Only the user\'s email | `service_auth` | required |',
  '| Neither | `anonymous` | optional, deferred |',
  '',
  'For `identity_assertion`, cross-check the assertion type against',
  '`identity_assertion.assertion_types_supported` before sending; if it is not listed, choose',
  'another method or stop.',
  '',
  '## 3. Register',
  '',
  'All three methods POST to `identity_endpoint`. Every response returns a service-signed',
  '`identity_assertion` — never a credential directly — which is exchanged at `token_endpoint`.',
  '',
  '### 3a. identity_assertion',
  '',
  '```http',
  'POST /oauth/agent/identity HTTP/1.1',
  'Host: www.typematchup.org',
  'Content-Type: application/json',
  '',
  '{',
  '  "type": "identity_assertion",',
  '  "assertion": "<ID-JAG bound to this audience>"',
  '}',
  '```',
  '',
  '```json',
  '{',
  '  "identity_assertion": "<service-signed JWT>",',
  '  "assertion_expires": 3600,',
  '  "scopes": ["type:read"]',
  '}',
  '```',
  '',
  'If the verified email matches an existing account the service returns `401 interaction_required`',
  'with a `claim` block; if `auth_time` is stale it returns `401 login_required`.',
  '',
  '### 3b. service_auth',
  '',
  '```http',
  'POST /oauth/agent/identity HTTP/1.1',
  'Host: www.typematchup.org',
  'Content-Type: application/json',
  '',
  '{',
  '  "type": "service_auth",',
  '  "login_hint": "user@example.com"',
  '}',
  '```',
  '',
  '```json',
  '{',
  '  "claim_token": "<opaque>",',
  '  "claim": {',
  '    "user_code": "ABCD-1234",',
  '    "verification_uri": "https://www.typematchup.org/oauth/claim",',
  '    "expires_in": 600',
  '  }',
  '}',
  '```',
  '',
  'No assertion yet: it is minted when the user completes the ceremony.',
  '',
  '### 3c. anonymous',
  '',
  '```http',
  'POST /oauth/agent/identity HTTP/1.1',
  'Host: www.typematchup.org',
  'Content-Type: application/json',
  '',
  '{ "type": "anonymous" }',
  '```',
  '',
  '```json',
  '{',
  '  "identity_assertion": "<service-signed JWT>",',
  '  "claim_token": "<opaque>",',
  '  "pre_claim_scopes": ["type:read"]',
  '}',
  '```',
  '',
  'The agent can exchange immediately and work at `pre_claim_scopes`; the user claims ownership later.',
  '',
  '## 4. Claim ceremony',
  '',
  'The service never emails a code: `user_code` travels from the agent to the user, and the user',
  'authenticates on a page the service owns.',
  '',
  '**4a. Get the ceremony materials.** `service_auth` already carries the `claim` block. For',
  '`anonymous`, POST the `claim_token` and the user\'s email to `claim_endpoint` to mint a',
  '`claim_attempt` block.',
  '',
  '**4b. Hand off to the user.** Surface `verification_uri` and `user_code` in one message. The',
  'user opens the link, signs in at the service, and types the code there — not back to the agent.',
  '',
  '**4c. Poll for completion.**',
  '',
  '```http',
  'POST /oauth2/token HTTP/1.1',
  'Host: www.typematchup.org',
  'Content-Type: application/x-www-form-urlencoded',
  '',
  'grant_type=urn:workos:agent-auth:grant-type:claim&claim_token=<claim_token>',
  '```',
  '',
  'Returns `authorization_pending` while waiting; on success a standard token response plus an',
  '`identity_assertion`. On `expired_token`, re-call `claim_endpoint` for a fresh code.',
  '',
  '## 5. Exchange the assertion',
  '',
  'RFC 7523 JWT-bearer exchange at `token_endpoint`:',
  '',
  '```http',
  'POST /oauth2/token HTTP/1.1',
  'Host: www.typematchup.org',
  'Content-Type: application/x-www-form-urlencoded',
  '',
  'grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=<identity_assertion>&resource=' +
    SITE,
  '```',
  '',
  'Response is a standard OAuth token envelope (`access_token`, `token_type`, `expires_in`, `scope`)',
  'with **no** `refresh_token`. The same assertion can be re-exchanged until it expires.',
  '',
  '## 6. Use the access_token',
  '',
  '```http',
  'GET /api/agent/search?q=charizard HTTP/1.1',
  'Host: www.typematchup.org',
  'Authorization: Bearer <access_token>',
  '```',
  '',
  'When the access token expires, re-exchange the same `identity_assertion`. When the assertion',
  'expires or `/oauth2/token` returns `invalid_grant`, restart at registration.',
  '',
  '## 7. Errors',
  '',
  '| Code | Returned by | Action |',
  '| --- | --- | --- |',
  '| `invalid_issuer` | `/oauth/agent/identity` | Use a listed issuer |',
  '| `invalid_signature` | `/oauth/agent/identity` | Re-sign the assertion |',
  '| `expired` | `/oauth/agent/identity` | Mint a fresh assertion |',
  '| `replay_detected` | `/oauth/agent/identity` | Do not retry unchanged |',
  '| `invalid_audience` | `/oauth/agent/identity` | Bind to this resource |',
  '| `invalid_client_id` | `/oauth/agent/identity` | Check the client id |',
  '| `missing_verified_email` | `/oauth/agent/identity` | Use `service_auth` or `anonymous` |',
  '| `*_not_enabled` | `/oauth/agent/identity` | Method opted out; pick another |',
  '| `interaction_required` | `/oauth/agent/identity` | Complete the claim ceremony |',
  '| `login_required` | `/oauth/agent/identity` | User must re-authenticate |',
  '| `invalid_claim_token` | `/oauth/agent/identity/claim` | Restart registration |',
  '| `claimed_or_in_flight` | `/oauth/agent/identity/claim` | Wait |',
  '| `claim_expired` | `/oauth/agent/identity/claim` | Mint a fresh code |',
  '| `authorization_pending` | `/oauth2/token` | Keep polling |',
  '| `expired_token` | `/oauth2/token` | Fresh `user_code` |',
  '| `slow_down` | `/oauth2/token` | Increase poll interval |',
  '| `invalid_grant` | `/oauth2/token` | Restart at registration |',
  '',
  '## 8. Revocation',
  '',
  'Two independent layers:',
  '',
  '- **Credential layer** (RFC 7009) — agent-callable. POST the access token to `revocation_endpoint`',
  '  to kill it. The `identity_assertion` survives, so a fresh access token can be minted.',
  '- **Registration layer** (RFC 8935 SET delivery to `events_endpoint`) — provider-driven. The',
  '  provider POSTs a `secevent+jwt` that invalidates the assertion and every token derived from it.',
  '  The agent observes this as `invalid_grant` on the next exchange and restarts at registration.',
  '',
  '## Contact',
  '',
  'This file: ' + AUTH_MD_URL + ' · Code and data: ' + REPO_URL,
  '',
].join('\n');
