// Dual-type pages in this list have a human-written strategy guide and are
// eligible for indexing. Calculator-only combinations remain accessible to
// users, but are deliberately kept out of search. Advertising is disabled sitewide
// during the content-quality review.
export const EDITORIAL_COMBINATIONS = new Set([
  'fire-flying',
  'steel-fairy',
  'water-ground',
  'ground-dragon',
  'flying-steel',
  'bug-steel',
  'poison-ghost',
  'water-psychic',
  'poison-dragon',
  'water-flying',
  'grass-poison',
  'dragon-flying',
  'water-electric',
  'psychic-dark',
  'psychic-fairy',
  'dragon-steel',
  'fire-fighting',
  'ground-ghost',
  'ground-flying',
  'flying-dark',
  'ice-ground',
  'poison-bug',
  'ground-rock',
  'grass-ice',
  'normal-flying',
  'bug-fairy',
  'grass-fairy',
  'ghost-dark',
  'ghost-steel',
  'dragon-ghost',
  'water-fighting',
  'water-grass',
  'fire-steel',
  'electric-dragon',
  'dragon-ice',
  'dragon-psychic',
  'fire-ground',
  'grass-dark',
  'grass-fighting',
  'poison-dark',
  'dark-steel',
  'dark-fairy',
  'fire-bug',
  'electric-steel',
  'electric-flying',
  'grass-steel',
  'ice-psychic',
  'fighting-dark',
  'fighting-psychic',
  'poison-fire',
  'flying-psychic',
  'water-rock',
  'fire-dark',
  'dragon-dark',
  'water-ice',
  'poison-fighting',
  'flying-bug',
  'fighting-rock',
]);

export function isEditorialCombination(slug: string): boolean {
  return EDITORIAL_COMBINATIONS.has(slug);
}
