import type { Metadata } from 'next';
import Link from 'next/link';
import EffectivenessExplorer from '@/components/EffectivenessExplorer';
import ToolNetwork from '@/components/ToolNetwork';
import JsonLd from '@/components/SEO/JsonLd';

const faqs = [
  ['How does Pokémon type effectiveness work?', 'Each attacking type has a 2×, 1×, 0.5×, or 0× relationship with each defending type. For a dual-type defender, multiply both relationships together.'],
  ['Which Pokémon have famous 4× weaknesses?', 'Examples include Rhyperior against Water and Grass, Gyarados against Electric, Charizard against Rock, Scizor against Fire, and Garchomp against Ice. Each example has a particular 4× weakness; this is not a claim that one Pokémon has three different 4× weaknesses.'],
  ['What is the difference between 0.25× and 0.5× damage?', 'A 0.5× result means one defending type resists the attack. A 0.25× result means both defending types resist it, so 0.5 × 0.5 = 0.25×.'],
  ['What types are immune to what?', 'Key immunities include Normal to Ghost, Ghost to Normal and Fighting, Ground to Electric, Flying to Ground, Dark to Psychic, Fairy to Dragon, and Steel to Poison.'],
];
export const metadata: Metadata = { title:'Pokemon Type Effectiveness Calculator — Exact Multipliers', description:'Pokemon type effectiveness calculator showing exact 4×, 2×, 1×, 0.5×, 0.25×, and 0× multipliers plus the complete calculation and 18×18 matrix.', alternates:{canonical:'/type-effectiveness-calculator'} };
export default function Page(){return <main className="container mx-auto px-4 py-8"><JsonLd data={{'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Pokemon Type Effectiveness Calculator',url:'https://www.typematchup.org/type-effectiveness-calculator',applicationCategory:'GameApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{'@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]}}/><header className="mx-auto mb-8 max-w-4xl text-center"><h1 className="text-3xl sm:text-5xl font-bold">Pokemon Type Effectiveness Calculator</h1><p className="mt-4 text-lg text-gray-700">See exactly how damage multipliers combine—4×, 2×, 1×, 0.5×, 0.25×, or immune.</p></header><EffectivenessExplorer/><div className="mx-auto mt-6 max-w-4xl text-center"><Link href="/#calculator" className="font-semibold text-blue-700 hover:underline">Use the Type Calculator to see every matchup category →</Link></div><article className="prose max-w-4xl mx-auto mt-12"><h2>How Pokémon Type Effectiveness Works</h2><p>The matrix compares the attacking move type with the defender. Super-effective attacks use 2×, resisted attacks 0.5×, immunities 0×, and all other interactions 1× before other battle modifiers.</p><h2>How Dual Type Multipliers Stack</h2><p>Multiply the interaction against each defending type. Fire attacking Bug/Steel is 2×2=4×. Electric attacking Water/Ground is 2×0=0× because Ground supplies an immunity.</p><h2>4× Weaknesses Explained</h2><p>A 4× weakness appears when both types share a weakness. Classic cases include Charizard versus Rock, Garchomp versus Ice, Gyarados versus Electric, Rhyperior versus Water or Grass, and Scizor versus Fire.</p><h2>How to Memorize Type Effectiveness</h2><p>Learn immunities first, then group intuitive relationships such as Water beating Fire and Ground, or Fire beating Grass and Ice. Use the matrix for exceptions and practice with the site&apos;s type quiz rather than memorizing 324 cells in isolation.</p><h2>Type Effectiveness FAQ</h2>{faqs.map(([q,a])=><section key={q}><h3>{q}</h3><p>{a}</p></section>)}</article><ToolNetwork current="/type-effectiveness-calculator"/></main>}
