import type { Metadata } from 'next';
import DualTypeExplorer from '@/components/DualTypeExplorer';
import ToolNetwork from '@/components/ToolNetwork';
import JsonLd from '@/components/SEO/JsonLd';

const faqs = [
  ['What is a rare dual type in Pokémon?', 'Normal/Ghost was historically limited to Hisuian Zorua and Hisuian Zoroark, while Ice/Fairy is strongly associated with Alolan Ninetales. Availability changes as new games and forms are released.'],
  ['What dual types have the most weaknesses?', 'Grass/Ice and Rock/Ice each have seven attacking-type weaknesses under the modern chart. Use the “Most weaknesses” sorting option above to compare all 153 combinations.'],
  ['How does a 4× weakness work?', 'If both defending types are weak to the same attacking type, the two 2× multipliers combine: 2 × 2 = 4× type effectiveness.'],
  ['What is a strong defensive dual type?', 'Steel/Fairy has only Fire and Ground weaknesses plus two immunities. Water/Ground has one weakness, Grass, but that weakness deals 4× damage. Stats, abilities, recovery, and format still matter.'],
];
export const metadata: Metadata = { title:'Pokémon Dual Type Chart — All 153 Combinations', description:'Interactive Pokémon dual type chart for all 153 combinations. Sort by weakness count and inspect 4× weaknesses, resistances, immunities, and example Pokémon.', alternates:{canonical:'/dual-type-chart'} };
export default function Page(){return <main className="container mx-auto px-4 py-8"><JsonLd data={{'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Pokémon Dual Type Chart',url:'https://www.typematchup.org/dual-type-chart',applicationCategory:'GameApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{'@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]}}/><header className="mx-auto mb-8 max-w-4xl text-center"><h1 className="text-3xl sm:text-5xl font-bold">Pokémon Dual Type Chart</h1><p className="mt-4 text-lg text-gray-700">Every dual-type combination&apos;s weaknesses, resistances, and immunities—sorted and explorable.</p></header><DualTypeExplorer/><article className="prose max-w-4xl mx-auto mt-12"><h2>What Is a Dual Type in Pokémon?</h2><p>A dual-type Pokémon has two types contributing to its defensive matchup. The same pair can create valuable resistances, new weaknesses, or an immunity that overrides the other type.</p><h2>How Dual Type Weaknesses Stack</h2><p>The final multiplier equals the first defensive multiplier multiplied by the second. Two weaknesses become 2×2=4×; two resistances become 0.5×0.5=0.25×. An immunity makes the result zero—for example, Electric into Water/Ground is 2×0=0×.</p><h2>Strong Defensive Dual Types</h2><p>Steel/Fairy offers two immunities and only two weaknesses. Water/Ground has only one weakness, though Grass deals 4×. Ghost/Dark has useful immunities. No typing is automatically best because stats, recovery, abilities, and legal formats decide how often it can switch.</p><h2>Rare Dual Type Combinations</h2><p>Normal/Ghost and Ice/Fairy have historically appeared on very few evolutionary lines. Rarity changes as new species and regional forms arrive, so treat it as a generation-specific observation rather than a permanent rule.</p><h2>Dual Type Chart FAQ</h2>{faqs.map(([q,a])=><section key={q}><h3>{q}</h3><p>{a}</p></section>)}</article><ToolNetwork current="/dual-type-chart"/></main>}
